### ISSUE TITLE
Tests are failing on Julia nightly 

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/PaddedMatrices.jl#10]
I just noticed that tests are passing on Julia 1.5 but failing on Julia nightly.

**Comment by DilumAluthge** [comment]
Example log: https://github.com/chriselrod/PaddedMatrices.jl/runs/1543487875

**Comment by chriselrod** [comment]
I cannot reproduce it locally on Julia master. A week or so ago, I could sometimes, but it would disappear when running the example that produced it a second time.
```julia
TypeError: in new, expected PtrArray{Tuple{Int64, StaticInt{8}}, (true, false), Float64, 2, 1, -1, (1, 2), Tuple{StaticInt{8}, StaticInt{80}}, Tuple{StaticInt{1}, StaticInt{1}}}, got a value of type PtrArray{Tuple{Int64, StaticInt{8}}, (true, true), Float64, 2, 1, -1, (1, 2), Tuple{StaticInt{8}, StaticInt{80}}, Tuple{StaticInt{1}, StaticInt{1}}}
```
FWIW, the types:
```julia
PtrArray{Tuple{Int64, StaticInt{8}}, (true, false), Float64, 2, 1, -1, (1, 2), Tuple{StaticInt{8}, StaticInt{80}}, Tuple{StaticInt{1}, StaticInt{1}}}
PtrArray{Tuple{Int64, StaticInt{8}}, (true, true), Float64, 2, 1, -1, (1, 2), Tuple{StaticInt{8}, StaticInt{80}}, Tuple{StaticInt{1}, StaticInt{1}}}
```
The [line of code](https://github.com/chriselrod/PaddedMatrices.jl/blob/04438b79862847cf4c8b398821517658c713e90a/src/views.jl#L88):
```julia
@inline function Base.view(A::StrideArray, i::Vararg{Union{Integer,AbstractRange,Colon},K}) where {K}
    StrideArray(view(A.ptr, i...), A.data)
end
```
The type of `A.ptr` is
```julia
PtrArray{Tuple{Int64, StaticInt{8}}, (true, true), Float64, 2, 1, -1, (1, 2), Tuple{StaticInt{8}, StaticInt{80}}, Tuple{StaticInt{1}, StaticInt{1}}}
```
and the type of `view(A.ptr, i...)` in this case is supposed to be
```julia
PtrArray{Tuple{Int64, StaticInt{8}}, (true, false), Float64, 2, 1, -1, (1, 2), Tuple{StaticInt{8}, StaticInt{80}}, Tuple{StaticInt{1}, StaticInt{1}}}
```
and that is what is was expecting, but sometimes it gets an object of the former type instead?

**Comment by DilumAluthge** [comment]
Looks like the only difference is the `(true, true)` versus the `(true, false)`, right?

What does that second Bool signify?

**Comment by chriselrod** [comment]
Whether that dimension is "dense".
Basically, if you have `A = rand(5,10)`, `A` is dense, and you can access it with LinearIndexing.
Similarly, `view(A, :, 3:5)` is also dense.

But `view(A, 3:5, :)` is `(true,false)`, because while the first axis doesn't have any gaps, the second one does.

But I still need to figure out how/why Julia may get confused about what to expect/receive.

**Comment by DilumAluthge** [comment]
I see what you mean. E.g. 
```julia
julia> A = rand(5,10);

julia> IndexStyle(A)
IndexLinear()

julia> IndexStyle(view(A, :, 3:5))
IndexLinear()

julia> IndexStyle(view(A, 3:5, :))
IndexCartesian()
```

**Comment by DilumAluthge** [comment]
So, is the bug here that we are expecting something that is not dense, but sometimes we are getting something that is dense?

**Comment by chriselrod** [comment]
Yeah, the idea of the `(true,false)` is to provide finer information to LoopVectorization so that it can make its own decisions:
```julia
julia> A = rand(5,10);

julia> IndexStyle(A)
IndexLinear()

julia> IndexStyle(A')
IndexCartesian()
```
If someone wrote a loop using `eachindex(A')`, but it's legal to use LinearIndexing instead, that tuple provides LoopVectorization the information it needs to make that decision.
I haven't implemented that yet -- it's planned for the rewrite -- but will be a nice optimization.

> So, is the bug here that we are expecting something that is not dense, but sometimes we are getting something that is dense?

I don't know.
Back when I could reproduce it (I cannot now), rerunning the exact same line of code that resulted in the error a second time -- without changing anything -- would then work as expected.

At the time, just adding this extra test:
https://github.com/chriselrod/PaddedMatrices.jl/commit/04438b79862847cf4c8b398821517658c713e90a
Made the error disappear on 1.5.
It's a Heisenbug. =/

**Comment by DilumAluthge** [comment]
I just reproduced it! But then I closed my Julia session by accident.

I was doing something like this: (on Julia master)
```julia
using PaddedMatrices, LinearAlgebra, Test

while true
    global A = @StrideArray rand(10,8);
    view(A, 1:StaticInt(6), :)
    print(".")
end
```

And I managed to get the `view` line to throw this same exception.

**Comment by chriselrod** [comment]
I figured it'd happen right away, or not at all. 
Did it take a while?

If we can find something that's reliable, we could file a Julia issue.

**Comment by DilumAluthge** [comment]
So, here's what I did:
1. I ran the while loop for a little while. I don't remember how long. Maybe 30 seconds, maybe a few minutes?
2. I interrupted with Ctrl-C, which brought me back to the REPL prompt
3. I ran the while loop again, and it immediately threw the exception, on the first iteration of the while loop

But now I am repeating those steps and I can't get it to happen again.

**Comment by DilumAluthge** [comment]
Also, I don't think I had that `global` in there.

**Comment by DilumAluthge** [comment]
Also I might have had some other stuff in the session, i.e. it wasn't a clean session.

**Comment by chriselrod** [comment]
Interesting. Can something like `rr` be used here to try and get a reproducible example for an issue?

**Comment by DilumAluthge** [comment]
> Back when I could reproduce it (I cannot now), rerunning the exact same line of code that resulted in the error a second time -- without changing anything -- would then work as expected.

This sounds a lot like a generated function problem, right? E.g. with generated functions, the compiler might choose to run the generated function the first time, but then cache the result. So the first time this line of code was run, the generated function was run, but the second time this line of code was run, the generated function was NOT run, and instead the cached result was used.

Maybe the generated function here (https://github.com/chriselrod/PaddedMatrices.jl/blob/6cf228b66b3250ac7660833e58db43ba6c504ead/src/views.jl#L10) is where the problem is?

Is there any chance that this generated function is doing something funny, like side effects, or non-deterministic behavior, or observing any mutable state or causing any mutation of global state, or anything like that?

**Comment by DilumAluthge** [comment]
> Interesting. Can something like `rr` be used here to try and get a reproducible example for an issue?

That seems like the right approach.

**Comment by DilumAluthge** [comment]
Is there any chance that https://github.com/chriselrod/PaddedMatrices.jl/blob/6cf228b66b3250ac7660833e58db43ba6c504ead/src/views.jl#L10 is not type-stable, i.e. is it possible that the contents of the `Expr` that it outputs are not completely by the types of the input?

**Comment by DilumAluthge** [comment]
Is there any chance that for https://github.com/chriselrod/PaddedMatrices.jl/blob/6cf228b66b3250ac7660833e58db43ba6c504ead/src/views.jl#L10, is it possible that there is a case in which the contents of the `Expr` that it outputs are not completely determined by the types of the input?

**Comment by chriselrod** [comment]
> , is it possible that there is a case in which the contents of the `Expr` that it outputs are not completely determined by the types of the input?

You don't have access to the actual values inside the generated body, so it'd have to be something like some sort of global state causing problems. I'll take an umpteenth look at that generated function.

**Comment by chriselrod** [comment]
You may be on to something. `densev` is a vector that turns into that `(true,true)` vs `(true,false)` tuple from the error.
```julia
            densev[spₙ] = still_dense
            if still_dense
                still_dense = (((ispₙ === Colon)::Bool || (ispₙ <: Base.Slice)::Bool) ||
                               ((ispₙ <:  ArrayInterface.OptionallyStaticUnitRange{<:StaticInt,<:StaticInt})::Bool &&
                                (static_length(ispₙ) == _extract(S.parameters[spₙ]))::Bool))
            end
```
Some of this, e.g. `static_length` and `_extract` are functions that're doing dispatches here.
Maybe the dispatches are changing, leading to a different answer?

But looking at `misc.jl`:
```julia
    A = @StrideArray rand(10,8);
    A_u = view(A, StaticInt(1):StaticInt(6), :)
    A_l = view(A, StaticInt(7):StaticInt(10), :)
    @test A == @inferred(vcat(A_u, A_l))
    @test PaddedMatrices.size(A) === PaddedMatrices.size(vcat(A_u, A_l))

    # On 1.5 tests fail if you don't do this first.
    @test pointer(view(A, 1:StaticInt(6), :)) == pointer(A)
    A_u = view(A, 1:StaticInt(6), :);
    A_l = view(A, StaticInt(7):StaticInt(10), :);
```
The correct answer is `(true,false)`. The view should not be `(true,true)` in any of these.

**Comment by chriselrod** [comment]
```julia
julia> view(view(A, StaticInt(1):StaticInt(8), 2:7), StaticInt(2):StaticInt(8), 2:5)
7×4 StrideMatrix{Tuple{StaticInt{7}, Int64}, (true, true), Float64, 1, -1, (1, 2), Tuple{StaticInt{8}, StaticInt{64}}, Tuple{StaticInt{1}, StaticInt{1}}, PaddedMatrices.MemoryBuffer{64, Float64}} with indices StaticInt{1}():StaticInt{1}():StaticInt{7}()×StaticInt{1}():StaticInt{1}():4:
 0.631721  0.0884384  0.975791   0.172733
 0.75887   0.844408   0.388882   0.573865
 0.439444  0.601413   0.456786   0.247474
 0.430162  0.107156   0.27433    0.237408
 0.143338  0.917741   0.0326358  0.495743
 0.326724  0.019005   0.427627   0.695504
 0.120386  0.450052   0.850949   0.20037

julia> view(view(A, StaticInt(1):StaticInt(8), 2:7), StaticInt(2):StaticInt(8), 2:5)
ispₙ = ispₙ = ispₙ = ERROR: task switch not allowed from inside staged nor pure functions
Stacktrace:
  [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
    @ Base ./task.jl:695
  [2] wait
    @ ./task.jl:764 [inlined]
  [3] uv_write(s::Base.TTY, p::Ptr{UInt8}, n::UInt64)
    @ Base ./stream.jl:992
  [4] unsafe_write(s::Base.TTY, p::Ptr{UInt8}, n::UInt64)
    @ Base ./stream.jl:1064
  [5] write
    @ ./strings/io.jl:185 [inlined]
  [6] print
    @ ./strings/io.jl:187 [inlined]
  [7] print(::Base.TTY, ::String, ::String, ::Vararg{String})
    @ Base ./strings/io.jl:46
  [8] println(::Base.TTY, ::String, ::Vararg{String})
    @ Base ./strings/io.jl:73
  [9] println(::String, ::String)
    @ Base ./coreio.jl:4
 [10] #s16#53
    @ ~/.julia/dev/PaddedMatrices/src/views.jl:61 [inlined]
 [11] var"#s16#53"(K::Any, S::Any, D::Any, T::Any, N::Any, C::Any, B::Any, R::Any, X::Any, O::Any, ::Any, A::Any, i::Any)
    @ PaddedMatrices ./none:0
 [12] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any})
    @ Core ./boot.jl:574
 [13] view(::StrideMatrix{Tuple{StaticInt{8}, StaticInt{8}}, (true, true), Float64, 1, 0, (1, 2), Tuple{StaticInt{8}, StaticInt{64}}, Tuple{StaticInt{1}, StaticInt{1}}, PaddedMatrices.MemoryBuffer{64, Float64}}, ::ArrayInterface.OptionallyStaticUnitRange{StaticInt{1}, StaticInt{8}}, ::UnitRange{Int64})
    @ PaddedMatrices ~/.julia/dev/PaddedMatrices/src/views.jl:89
 [14] top-level scope
    @ REPL[13]:1

julia> view(view(A, StaticInt(1):StaticInt(8), 2:7), StaticInt(2):StaticInt(8), 2:5)
ispₙ = ArrayInterface.OptionallyStaticUnitRange{StaticInt{1}, StaticInt{8}}
ArrayInterface.known_length(ispₙ) = 8
_extract(S.parameters[spₙ]) = 8
S.parameters[spₙ] = StaticInt{8}
ispₙ = UnitRange{Int64}
ArrayInterface.known_length(ispₙ) = nothing
_extract(S.parameters[spₙ]) = 8
S.parameters[spₙ] = StaticInt{8}
ispₙ = ArrayInterface.OptionallyStaticUnitRange{StaticInt{2}, StaticInt{8}}
ArrayInterface.known_length(ispₙ) = 7
_extract(S.parameters[spₙ]) = 8
S.parameters[spₙ] = StaticInt{8}
7×4 StrideMatrix{Tuple{StaticInt{7}, Int64}, (true, false), Float64, 1, -1, (1, 2), Tuple{StaticInt{8}, StaticInt{64}}, Tuple{StaticInt{1}, StaticInt{1}}, PaddedMatrices.MemoryBuffer{64, Float64}} with indices StaticInt{1}():StaticInt{1}():StaticInt{7}()×StaticInt{1}():StaticInt{1}():4:
 0.631721  0.0884384  0.975791   0.172733
 0.75887   0.844408   0.388882   0.573865
 0.439444  0.601413   0.456786   0.247474
 0.430162  0.107156   0.27433    0.237408
 0.143338  0.917741   0.0326358  0.495743
 0.326724  0.019005   0.427627   0.695504
 0.120386  0.450052   0.850949   0.20037
```
It was incorrectly `(true,true)`!
When I added print statements to try and find out why, after the usual task-switching not allowed error, it switched to `(true,false)`.

I have no idea how could it have returned `(true,true)`.

**Comment by chriselrod** [comment]
If it doesn't go away after my latest commit, I'll try making the `densev` checks use explicit `.parameters` extractions, eg:
`StaticInt{4}.parameters[1]`
instead of taking the `_extract` and `known_length`/`static_length` approach.

**Comment by DilumAluthge** [comment]
> If it doesn't go away after my latest commit, I'll try making the `densev` checks use explicit `.parameters` extractions, eg:
> `StaticInt{4}.parameters[1]`
> instead of taking the `_extract` and `known_length`/`static_length` approach.

Might be worth doing that anyway.

Also, instead of doing `foo.bar`, might be better to do `getfield(foo, :bar)`.

`foo.bar` can be overloaded by overloading `getproperty(foo, :bar)`. But `getfield` can't be overloaded.

**Comment by chriselrod** [comment]
I made those changes locally, but I'm still seeing the problem.
This seems to reliably reproduce the issue of getting `(true,true)` when the last view should be `(true,false)` on the last one:
```julia
julia> using PaddedMatrices
[ Info: Precompiling PaddedMatrices [aaaacae8-1622-11e9-2a5c-532679323890]

julia> A = @StrideArray rand(8,8)
8×8 StrideMatrix{Tuple{StaticInt{8}, StaticInt{8}}, (true, true), Float64, 1, 0, (1, 2), Tuple{StaticInt{8}, StaticInt{64}}, Tuple{StaticInt{1}, StaticInt{1}}, PaddedMatrices.MemoryBuffer{64, Float64}} with indices StaticInt{1}():StaticInt{1}():StaticInt{8}()×StaticInt{1}():StaticInt{1}():StaticInt{8}():
 0.152575  0.0898079  0.201923  0.793662   0.167727  0.756744   0.487499  0.823384
 0.408584  0.0697494  0.537379  0.14461    0.417457  0.230299   0.518366  0.666196
 0.176401  0.326409   0.330925  0.709532   0.373459  0.804489   0.24513   0.406972
 0.120794  0.14655    0.109593  0.502438   0.862878  0.182679   0.665296  0.87001
 0.235808  0.598829   0.24007   0.0443999  0.314628  0.445555   0.134767  0.174351
 0.250546  0.38761    0.524279  0.980768   0.147412  0.0016011  0.112075  0.49419
 0.678873  0.588159   0.303478  0.386372   0.622147  0.728109   0.102349  0.89562
 0.257764  0.703234   0.46447   0.246221   0.770442  0.015817   0.638182  0.164859

julia> view(view(A, StaticInt(1):StaticInt(8), 2:7), StaticInt(2):StaticInt(8), 2:5)
7×4 StrideMatrix{Tuple{StaticInt{7}, Int64}, (true, false), Float64, 1, -1, (1, 2), Tuple{StaticInt{8}, StaticInt{64}}, Tuple{StaticInt{1}, StaticInt{1}}, PaddedMatrices.MemoryBuffer{64, Float64}} with indices StaticInt{1}():StaticInt{1}():StaticInt{7}()×StaticInt{1}():StaticInt{1}():4:
 0.537379  0.14461    0.417457  0.230299
 0.330925  0.709532   0.373459  0.804489
 0.109593  0.502438   0.862878  0.182679
 0.24007   0.0443999  0.314628  0.445555
 0.524279  0.980768   0.147412  0.0016011
 0.303478  0.386372   0.622147  0.728109
 0.46447   0.246221   0.770442  0.015817

julia> view(view(A, StaticInt(1):StaticInt(8), 2:7), StaticInt(1):StaticInt(8), 2:5)
8×4 StrideMatrix{Tuple{StaticInt{8}, Int64}, (true, true), Float64, 1, -1, (1, 2), Tuple{StaticInt{8}, StaticInt{64}}, Tuple{StaticInt{1}, StaticInt{1}}, PaddedMatrices.MemoryBuffer{64, Float64}} with indices StaticInt{1}():StaticInt{1}():StaticInt{8}()×StaticInt{1}():StaticInt{1}():4:
 0.201923  0.793662   0.167727  0.756744
 0.537379  0.14461    0.417457  0.230299
 0.330925  0.709532   0.373459  0.804489
 0.109593  0.502438   0.862878  0.182679
 0.24007   0.0443999  0.314628  0.445555
 0.524279  0.980768   0.147412  0.0016011
 0.303478  0.386372   0.622147  0.728109
 0.46447   0.246221   0.770442  0.015817

julia> view(view(A, StaticInt(1):StaticInt(8), 2:7), StaticInt(1):StaticInt(7), 2:5)
7×4 StrideMatrix{Tuple{StaticInt{7}, Int64}, (true, true), Float64, 1, -1, (1, 2), Tuple{StaticInt{8}, StaticInt{64}}, Tuple{StaticInt{1}, StaticInt{1}}, PaddedMatrices.MemoryBuffer{64, Float64}} with indices StaticInt{1}():StaticInt{1}():StaticInt{7}()×StaticInt{1}():StaticInt{1}():4:
 0.201923  0.793662   0.167727  0.756744
 0.537379  0.14461    0.417457  0.230299
 0.330925  0.709532   0.373459  0.804489
 0.109593  0.502438   0.862878  0.182679
 0.24007   0.0443999  0.314628  0.445555
 0.524279  0.980768   0.147412  0.0016011
 0.303478  0.386372   0.622147  0.728109
```
Adding/removing print statements that don't change anything else will cause the type to switch back and forth between `(true,true)` and `(true,false)`. =/

For reference, the four arrays above should be `(true,true),(true,false),(true,true),(true,false)`.

**Comment by chriselrod** [comment]
lol, found the bug
```julia
densev = Vector{Bool}(undef, K)
```
and then I didn't actually write to it on every branch of a loop.
Hence, uninitialized memory -> random switching between `true` and `false`.

That took me way longer to find than it should have. =/

**Comment by DilumAluthge** [comment]
Whew! What a saga.
