### ISSUE TITLE
Add DOCUMENTER_KEY

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/PaddedMatrices.jl#11]
@chriselrod Can you add the DOCUMENTER_KEY for this repo? Here are the steps:

1. `Pkg.add("DocumenterTools")`
2. `DocumenterTools.genkeys()`
3. Take the Base64-encoded private key from step 2 and add it to this repo as a GitHub Secret (https://github.com/chriselrod/PaddedMatrices.jl/settings/secrets/actions) named `DOCUMENTER_KEY`.
4. Take the corresponding public key from step 2 and add it to this repo as a deploy key (https://github.com/chriselrod/PaddedMatrices.jl/settings/keys) named `DOCUMENTER_KEY_PUBLIC`. Make sure that the deploy key has **write access**.

**Comment by chriselrod** [comment]
Note though that I haven't actually created docs yet, but I'll do this for when.

**Comment by chriselrod** [comment]
https://chriselrod.github.io/PaddedMatrices.jl/dev/
